apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nfs-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: pvc-test #
        persistentVolumeClaim:
          claimName: pvc-test  # same name of pvc that was created
      containers:
      - image: docker-hub.artifactory.srv.westpac.com.au/nginx
        name: nginx
        volumeMounts:
        - name: pvc-test # name of volume should match claimName volume
          mountPath: mydata2 # mount inside of contianer
